language: python
cache: pip

matrix:
  include:
    - { python: '3.6', env: TOXENV=py36 }
    - { arch: arm64, python: '3.6', env: TOXENV=py36 }
# Avoid overriding the default install step,
# so that automatic pip caching works.
#
# See: https://github.com/travis-ci/travis-ci/issues/3239
#
before_script:
  - pip install tox

script:
  - tox
